---
name: sirgantmusic
locales: [en]
seo_title: sirgantmusic
meta_keywords: sir,gant,journey,anita,madonna,keyboardist,composer
meta_description: The official site of Dean Gant aka Sir Gant.
timezone: Eastern Time (US & Canada)
