# TODO: explain it
name: sirgantmusic

# TODO: explain it
# subdomain: sample

# TODO: explain it
# domains: [www.example.com, example.com]

# TODO: explain it
locales: [en]

# TODO: explain it
seo_title: sirgantmusic
meta_keywords: "sir,gant,journey,anita,madonna,keyboardist,composer"
meta_description: "The official site of Dean Gant aka Sir Gant."
