source 'https://rubygems.org'

gem 'rails', '3.2.16'

gem 'locomotive_cms', '~> 2.4.1', :require => 'locomotive/engine'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'compass-rails',  '~> 1.0.2'
  gem 'sass-rails',     '~> 3.2.4'
  gem 'coffee-rails',   '~> 3.2.2'
  gem 'uglifier',       '~> 1.2.4'
end


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
group :development do
  gem 'unicorn'
end
# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
